//Development
###
GET http://localhost:3000/
###

GET http://localhost:3000/users/
###

GET http://localhost:3000/docs/

###
GET http://localhost:3000/users/6717af075ae4e2146931b6a0

###
GET http://localhost:3000/docs/6717af075ae4e2146931b6a0

###
POST http://localhost:3000/users/ HTTP/1.1
content-type: application/json

{   
    "user":{
    "firstName": "Luz",
    "lastName": "Chino",
    "email": "Luz@byui.com",
    "level": "admin1"
    }
}

###
PUT http://localhost:3000/contacts/67131873a0510839ba0387dd HTTP/1.1
content-type: application/json

{
    "firstName":"Hessed",
    "lastName":"Chino",
    "email":"test@gmail.com",
    "favoriteColor":"Red",
    "birthday":"12/12/24"
}
### DELETE contact
DELETE http://localhost:3000/contacts/67131873a0510839ba0387dd HTTP/1.1

// Production

###
https://cse341-04.onrender.com/

###
https://cse341-04.onrender.com/contacts

###
https://cse341-04.onrender.com/contacts/6717120629810ddfa37595f2

###
POST https://cse341-04.onrender.com/users/ HTTP/1.1
content-type: application/json

{   "user":{
    "firstName": "Helaman",
    "lastName": "Chino",
    "email": "helamchino@byui.com",
    "level": "admin2"
    }
}

###
PUT https://cse341-04.onrender.com/contacts/6717120629810ddfa37595f2 HTTP/1.1
content-type: application/json

{
    "firstName":"Helaman",
    "lastName":"Chino",
    "email":"test@gmail.com",
    "favoriteColor":"Red",
    "birthday":"12/12/24"
}
### DELETE contact
DELETE https://cse341-04.onrender.com/contacts/6717120629810ddfa37595f2 HTTP/1.1

